title: Project:道仙朋克
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://github.com/project-taoistpunk

aux_links:
  "Github主页": https://github.com/project-taoistpunk/project-taoistpunk.github.io

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.2.3"
