title: 山风有露-车库
description: 羊花后花园
theme: just-the-docs

url: https://github.com/project-taoistpunk

aux_links:
  "Lofter主页": https://irisweish.lofter.com/

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.2.3"

callouts:
  warning:
    title: Warning
    color: red
  highlight:
    title: Highlight
    color: blue